### ISSUE TITLE
Unable to display the double skin added by Et Futurum Requiem

### ISSUE THREAD

**Issue by ArchiDreamZ** [KAMKEEL/MorePlayerModels-Plus#10]
I used Et Futurum Requiem, which allowed me to render a double skinned body in 1.7.10, like this:
![image](https://user-images.githubusercontent.com/89504984/233999083-5f8cd951-b22e-4f0c-8345-c63adf562eb9.png)

But when I add MPM or MPM+, it won't allow me to display double skin：
![image](https://user-images.githubusercontent.com/89504984/233999548-78b963ae-2b97-4a0b-babc-fdd08a7f73cd.png)

**Comment by KAMKEEL** [comment]
In Et-Futurum config  you will need to disable 1.8 skins! Go to MPM+ and change your Model Type to `Steve64` or `Alex` then go into BODY/ARMS/LEGS/HEAD configs and you can enable your 3D Layers!
