### ISSUE TITLE
Broken Player skins and an incompatibility with lumys skin patch?

### ISSUE THREAD

**Issue by 20Whey** [KAMKEEL/MorePlayerModels-Plus#11]
the incompatability is less of an issue, as should the bug causing the player skins be fixed lumy's wouldn't be needed. -lumys being present does crash your client.

your skin resets upon logging in, but if you change your view it becomes a default steve skin with image3's error

images in order from logging in.
![image1](https://github.com/KAMKEEL/MorePlayerModels-Plus/assets/31368984/56096867-5779-45bf-9b2d-7ba7073a7b95)
![image2](https://github.com/KAMKEEL/MorePlayerModels-Plus/assets/31368984/b887b8c0-5159-453f-ad5b-dcf6d1455f18)
![image3](https://github.com/KAMKEEL/MorePlayerModels-Plus/assets/31368984/d51cc06b-6514-4b35-b203-e8bf9237c5a8)

**Comment by KAMKEEL** [comment]
i think this is fixed
