### ISSUE TITLE
Some render-related crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [KAMKEEL/MorePlayerModels-Plus#3]
Getting some render crash. Mods in report.

https://pastebin.com/hix03ks7

**Comment by KAMKEEL** [comment]
Please check the latest version of MPM+ **2.0** HERE: https://www.curseforge.com/minecraft/mc-mods/moreplayermodels-plus/files/4111996
Let me know if this still occurs. I feel this was a syncing issue that was patched now

**Comment by MagmaBro123** [comment]
Seems to be fixed.
