### ISSUE TITLE
[Question] does it work with MPM bukkit plugin?

### ISSUE THREAD

**Issue by HowardZHY** [KAMKEEL/MorePlayerModels-Plus#5]

**Comment by HowardZHY** [comment]
damn no

**Comment by MagmaSlime123** [comment]
MPM isn't a plugin. If you're talking about LibsDisguises, then no.

**Comment by HowardZHY** [comment]
I mean this one https://dev.bukkit.org/projects/sit-and-lie-anywhere

**Comment by KAMKEEL** [comment]
Yes, MPM+ is an extension so the originally MPM. I don't think I changed anything that would break compatibility with MPM Bukkit. But, you should try it and post it here if it does or doesn't. Then I can fix it if it doesn't.
