### ISSUE TITLE
Support for Smart Moving

### ISSUE THREAD

**Issue by MagmaSlime123** [KAMKEEL/MorePlayerModels-Plus#6]
Support for https://github.com/makamys/SmartMoving/ fork.
Uses: Smart Render, PlayerAPI, _optional_: RenderPlayerAPI

**Comment by KAMKEEL** [comment]
https://discord.com/channels/916447407573700648/1009312250508611604/1063562715244793996

I believe it may be easier to patch this VIA SmartMoving's end, but even so, I would need help on something like this as I'm not versed well enough to achieve this alone.

**Comment by MagmaSlime123** [comment]
Ah, alright.
