### ISSUE TITLE
Animation bug when you sit down

### ISSUE THREAD

**Issue by Lundashy** [KAMKEEL/MorePlayerModels-Plus#9]
I found a bug, when the player sits down the sitting animation doesn't appear correctly in the minecart or when you ride a horse, it also happens in mods where they add chairs.

I tested it with the latest version of the mod "MorePlayerModels+ v2.1" only with forge 10.13.4.1614.

Have a nice day! ^^
![2023-04-06_16 54 21](https://user-images.githubusercontent.com/108596963/230481370-90150db1-8bf7-42bb-abfb-e4ab5e6e5255.png)
![2023-04-06_16 55 25](https://user-images.githubusercontent.com/108596963/230481376-2ca6f393-5860-4153-846a-17bd76bb50be.png)
![2023-04-06_16 55 59](https://user-images.githubusercontent.com/108596963/230481378-1e28134c-d641-4712-8fd2-3d4d9d128a3f.png)

**Comment by KAMKEEL** [comment]
Yep, I'm aware of this issue! It will be fixed thank you :)

**Comment by KAMKEEL** [comment]
Closing! Patched version will be released soon!
